# Generated by Django 5.2.4 on 2025-07-22 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='loyalty_tier',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='donor',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='donor',
        ),
        migrations.AlterModelOptions(
            name='auctionitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='auctionitem',
            old_name='end_time',
            new_name='ends_at',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='blockchain_tx',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='blockchain_tx',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='blockchain_tx',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='impact_report',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient_code',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='ai_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='blockchain_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('monetary', 'Monetary'), ('item', 'Item')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ai_priority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='diagnosis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='needs',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='DonorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze Champion'), ('silver', 'Silver Champion'), ('gold', 'Gold Champion'), ('platinum', 'Platinum Champion')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_hash', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auction_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.auctionitem')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LoyaltyTier',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
