# Generated by Django 5.2.4 on 2025-08-26 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_donor_loyalty_tier_remove_donor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=1)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', '-ai_confidence'],
            },
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='ai_categorization_confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='ai_last_categorized',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='ai_relevance_score',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ai_analysis_confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ai_last_analyzed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ai_needs_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ai_urgency_score',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('patient', 'Patient Recommendation'), ('donor', 'Donor Recommendation'), ('matching', 'Patient-Donor Matching')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('relevance_score', models.FloatField(default=0.0)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auction_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='api.auctionitem')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='api.patientprofile')),
            ],
            options={
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
    ]
